// <auto-generated />
using EncurtadorDeLinks.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EncurtadorDeLinks.Migrations
{
    [DbContext(typeof(EncurtadorContext))]
    partial class EncurtadorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EncurtadorDeLinks.Models.URL", b =>
                {
                    b.Property<string>("_URL")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Short_URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Time_URL")
                        .HasColumnType("int");

                    b.HasKey("_URL");

                    b.ToTable("URLS");
                });
#pragma warning restore 612, 618
        }
    }
}
